services:
  db:
    image: postgres:15-alpine
    container_name: ai_workshop_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-ai_workshop}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mysecretpassword}
    ports:
      - '${DB_PORT_EXTERNAL:-5438}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ai_workshop_api
    restart: always
    volumes:
      - ./server:/app
      - /app/node_modules
    command: pnpm dev
    ports:
      - '${PORT:-3000}:3000'
    environment:
      NODE_ENV: development
      PORT: ${PORT:-3000}
      DB_NAME: ${DB_NAME:-ai_workshop}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-mysecretpassword}
      DB_HOST: db
      DB_PORT: ${DB_PORT_INTERNAL:-5432}
      TOKEN_KEY: ${TOKEN_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ai_workshop_client
    restart: always
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - api

volumes:
  postgres_data:
